### ISSUE TITLE
CodeStyle

### ISSUE THREAD

**Issue by Grafeeva** [nautilusnsk/Task_8#6]
1. Рекомендуется придерживаться единого стиля во всем проекте.
2. Рекомендуется удалять “мусор” (код), который автоматически генерируется при создании проекта/файлов, для того, чтобы не акцентировать на себе внимание. Пример: неиспользуемые методы в AppDelegate (applicationDidBecomeActive, applicationWillTerminate, и т.д.) или в RepositoryTableViewCell (awakeFromNib, setSelected)
3.  Местами встречаются обращение к property в виде `self.repositories?.count` (рекомендуется не писать это везде, где можно этого избежать). 
4. Желательно, чтобы длина строки не превышала 100 символов.

**Comment by ker1o** [comment]
поменял стиль оформления замыканий, почистил мусор, постарался везде не превышать 100 символов, но не везде получается. 4-ый наверно самый сложный пункт )
